# {dotfiles}/bombadil.toml

# Path to your dotfiles relative to your $HOME directory
dotfiles_dir = "dotfiles"

[settings]
posthooks = [ "bspc wm -r", "pkill -USR1 -x sxhkd" ]
	

[settings.dots]
fontconfig = { source = "fontconfig", target = ".config/fontconfig" }
clangd = { source = "clangd", target = ".config/clangd" }
gtk3 = { source = "gtk/gtk-3.0", target = ".config/gtk-3.0" }
kitty = { source = "kitty", target = ".config/kitty" }
nvim = { source = "nvim", target = ".config/nvim" }
mpd = { source = "mpd/mpd.conf", target = ".config/mpd/mpd.conf" }
mpv = { source = "mpv", target = ".config/mpv" }
ncb = { source = "ncmpcpp/bindings", target = ".config/ncmpcpp/bindings" }
ncc = { source = "ncmpcpp/config", target = ".config/ncmpcpp/config" }
neofetch = { source = "neofetch", target = ".config/neofetch" }
ranger = { source = "ranger", target = ".config/ranger" }
redshift = { source = "redshift", target = ".config/redshift" }
wal = { source = "wal", target = ".config/wal" }
zathura = { source = "zathura", target = ".config/zathura" }

cpxc = { source = "scripts/connect_pxc.sh", target = "scripts/connect_pxc.sh" }
dpxc = { source = "scripts/disconnect_pxc.sh", target = "scripts/disconnect_pxc.sh" }
kbsetup = { source = "scripts/keyboard-setup.sh", target = "scripts/keyboard-setup.sh" }
osh = { source = "scripts/osuhelper.sh", target = "scripts/osuhelper.sh" }
ppxc = { source = "scripts/pair_pxc.sh", target = "scripts/pair_pxc.sh" }
pyps = { source = "scripts/pyps.sh", target = "scripts/pyps.sh" }
rea = { source = "scripts/rearchive.sh", target = "scripts/rearchive.sh" }
setbg = { source = "scripts/setbg.sh", target = "scripts/setbg.sh" }
sp = { source = "scripts/sp", target = "scripts/sp" }
xauto = { source = "scripts/xautostart.sh", target = "scripts/xautostart.sh" }
xev = { source = "scripts/xev.sh", target = "scripts/xev.sh" }
ycmd = { source = "scripts/ycmd.sh", target = "scripts/ycmd.sh" }
yt = { source = "scripts/yt.sh", target = "scripts/yt.sh" }
ytarchive = { source = "scripts/ytarchive.sh", target = "scripts/ytarchive.sh" }
ytaudio = { source = "scripts/ytaudio.sh", target = "scripts/ytaudio.sh" }

xdg = { source = "xdg/user-dirs.dirs", target = ".config/user-dirs.dirs" }
gitconfig = { source = "git/.gitconfig", target = ".gitconfig" }
gtk2 = { source = "gtk/.gtkrc-2.0", target = ".gtkrc-2.0" }
zprofile = { source = "zsh/.zprofile", target = ".zprofile" }
zshrc = { source = "zsh/.zshrc", target = ".zshrc" }

bspwm = { source = "bspwm", target = ".config/bspwm" }
polybar = { source = "polybar", target = ".config/polybar" }
rofi = { source = "rofi", target = ".config/rofi" }
sxhkd = { source = "sxhkd", target = ".config/sxhkd" }

betterlockscreen = { source = "betterlockscreen/betterlockscreenrc", target = ".config/betterlockscreenrc" }
screenlayout = { source = "screenlayout", target = ".screenlayout" }
xinitrc = { source = "x11/.xinitrc", target = ".xinitrc" }
xmodmap = { source = "x11/.Xmodmap", target = ".Xmodmap" }


[profiles.desktop]

vars = [ "vars/base.toml", "vars/desktop.toml" ]


[profiles.laptop]

vars = [ "vars/base.toml", "vars/laptop.toml" ]
