[monitor]
left = "HDMI-0"
main = "DP-2"
right = "DP-4"

[mpd]
using = "true"

[bspwm]
border_width = "4"
top_padding = "50"
bottom_padding = "10"
left_padding = "10"
right_padding = "10"
window_gap = "15"

[polybar]
using_center = "true"
using_left = "true"
using_right = "false"
network_device = "wlp6s0"

[xrandr]
script = "~/.screenlayout/gatech.sh"

[browser]
cmd = "brave"

